### ISSUE TITLE
Docker image it's not found

### ISSUE THREAD

**Issue by giannaccio** [hyper-expanse/semantic-delivery-gitlab#11]
Using url 
- registry.gitlab.com/hyper-expanse/open-source/semantic-delivery-gitlab:9.0.0
the pipeline it's broken (error it's access denied)

We also tried to open urls
- https://gitlab.com/hyper-expanse/open-source/semantic-delivery-gitlab/container_registry
- registry.gitlab.com/hyper-expanse/open-source/semantic-delivery-gitlab:9.0.0
the error is 404

**Comment by hutson** [comment]
@giannaccio and @wargamez my apologies for breaking your workflows by deleting my GitLab repositories. In my effort to consolidate my source code accounts, I inadvertently "re-discovered" the perils of re-using the same host for both source code management, and binary artifact storage.

I have re-published docker images for this project to Docker Hub - https://hub.docker.com/repository/docker/hutson/semantic-delivery-gitlab/general

Some of the digests, content hashes, may be different between the newly published docker images, and the previous images on GitLab. My setup is not sufficiently deterministic to guarantee perfect reproducible builds.
