### ISSUE TITLE
Error: No valid "repository" data found in package metadata.

### ISSUE THREAD

**Issue by Mistic92** [hyper-expanse/semantic-delivery-gitlab#24]
Hi, I'm trying to use this on Gitlab CI both using docker and npm but for docker I'm getting error
```
semantic-delivery-gitlab failed for the following reason - Error: No valid "repository" data found in package metadata. Please see https://docs.npmjs.com/files/package.json#repository for proper syntax.
```

**Comment by hutson** [comment]
@Mistic92 that error message implies that your project has a top-level `package.json` file, but the file does not contain a `repository` field (Or at least, does not contain a valid `repository` field).

Please see the following `npm` documentation describing the proper format for the `repository` field - https://docs.npmjs.com/files/package.json#repository
