### ISSUE TITLE
High Vuln as a result of dot-prop

### ISSUE THREAD

**Issue by cyberserfer** [hyper-expanse/semantic-delivery-gitlab#45]
Just a heads up:

![Screen Shot 2020-07-31 at 3 33 59 PM](https://user-images.githubusercontent.com/22548275/89075627-3e9dfe80-d344-11ea-81ac-e41e9dafd933.png)

**Comment by hutson** [comment]
It appears we are waiting on this Pull Request to be reviewed and accepted - https://github.com/conventional-changelog/releaser-tools/pull/166

**Comment by hutson** [comment]
Unfortunately I have not had the time to properly investigate and address the security alert reported in one of this project's deep dependencies. This reflects directly on my inability to allocate the time this project requires to make it available and useful to the community. As a result, and to avoid users from depending on an unsupported project, I am moving forward with deprecating the package on the NPM registry and archiving this repository. Please consider migrating to another supported automated release tool.
