### ISSUE TITLE
How to change the tag format?

### ISSUE THREAD

**Issue by virgilwashere** [hyper-expanse/semantic-delivery-gitlab#51]
My existing repo has `v2.1.0` tags, 

```console
$ git tag -l
1.2.0
v1.3.0
v1.3.1
v1.3.2
v1.3.3
v1.3.5
v2.0.0
v2.0.1
v2.0.2
v2.0.3
v2.0.4
v2.0.5
v2.1.0
v2.1.0-rc.0
v2.1.0-rc.1
v2.1.0-rc.2
```

but `semantic-delivery-gitlab` wants to create `2.1.1` for a _patch_

```console
$ DEBUG=semantic-delivery-gitlab npx semantic-delivery-gitlab --dry-run -t $GITLAB_TOKEN
  semantic-delivery-gitlab latest tag v2.1.0 +0ms
  semantic-delivery-gitlab commit messages - [ 'chore(ci): add pipeline\n\n' ] +9ms
  semantic-delivery-gitlab detected angular commit convention +2ms
  semantic-delivery-gitlab using angular commit convention +0ms
  semantic-delivery-gitlab recommended version bump is - {
  semantic-delivery-gitlab   level: 2,
  semantic-delivery-gitlab   reason: 'There are 0 BREAKING CHANGES and 0 features',
  semantic-delivery-gitlab   releaseType: 'patch'
  semantic-delivery-gitlab } +22ms
  semantic-delivery-gitlab version to be released 2.1.1 +1ms
  semantic-delivery-gitlab posting release to 'https://gitlab.example.net/api/v4/' using preset 'angular' +0ms
  semantic-delivery-gitlab posting to the following issues - [] +0ms
Deleted tag '2.1.1' (was c68a122)
No release created during dry run.
```

**Comment by hutson** [comment]
@virgilwashere that is because `semantic-delivery-gitlab` does not support release candidates.

The code to increment the version number is `semver.inc(tags[0], recommendation.releaseType)`.

The `releaseType` property is always `patch`, `minor`, or `major`. 

We never pass in `prerelease` as an additional argument to generate pre-releases. 

It's a feature that would be nice to have, but I have not had the time to implement it.

**Comment by hutson** [comment]
Unfortunately I have not had the time to properly investigate and address the security alert reported in one of this project's deep dependencies. This reflects directly on my inability to allocate the time this project requires to make it available and useful to the community. As a result, and to avoid users from depending on an unsupported project, I am moving forward with deprecating the package on the NPM registry and archiving this repository. Please consider migrating to another supported automated release tool.
